/* API constants */

const API_KEY = "5874acfd11651a28c55771624f7021f4";
const API_URL = "https://api.themoviedb.org/3";
const API_TOP_RATED = `${API_URL}/movie/popular?api_key=${API_KEY}&language=en-US&page=1`;

const POSTER_URL = `https://image.tmdb.org/t/p/w500/`;

export const API = {
	API_KEY,
	API_URL,
	API_TOP_RATED,
	POSTER_URL
};

/* Redux Action Constants */

// App

export const appConstants = {
	SET_DRAWER_OPEN: 'SET_DRAWER_OPEN',

	SET_NOTIFICATION: 'SET_NOTIFICATION', 
	DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION', 
};

// Movie

export const moviesConstants = {
	GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
	GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
	GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE"
};

// Auth

export const authConstants = {
	LOGIN_REQUEST: "USER_LOGIN_REQUEST",
	LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
	LOGIN_FAILURE: "USER_LOGIN_FAILURE",

	LOGOUT: "USER_LOGOUT"
};

// Content

export const contentConstants = {
	GET_CONTENT_REQUEST: "GET_CONTENT_REQUEST",
	GET_CONTENT_SUCCESS: "GET_CONTENT_SUCCESS",
	GET_CONTENT_FAILURE: "GET_CONTENT_FAILURE",

	GET_CONTENT_BY_ID_REQUEST: "GET_CONTENTBY_ID_REQUEST",
	GET_CONTENT_BY_ID_SUCCESS: "GET_CONTENTBY_ID_SUCCESS",
	GET_CONTENT_BY_ID_FAILURE: "GET_CONTENTBY_ID_FAILURE",

	CREATE_REQUEST: "CONTENT_CREATE_REQUEST",
	CREATE_SUCCESS: "CONTENT_CREATE_SUCCESS",
	CREATE_FAILURE: "CONTENT_CREATE_FAILURE",

	UPDATE_REQUEST: "CONTENT_UPDATE_REQUEST",
	UPDATE_SUCCESS: "CONTENT_UPDATE_SUCCESS",
	UPDATE_FAILURE: "CONTENT_UPDATE_FAILURE",

	DELETE_REQUEST: "CONTENT_DELETE_REQUEST",
	DELETE_SUCCESS: "CONTENT_DELETE_SUCCESS",
	DELETE_FAILURE: "CONTENT_DELETE_FAILURE",

	REMOVE_EDIT_DATA: "REMOVE_EDIT_DATA"
};
